### ISSUE TITLE
[Feature Request] Show what game versions and mod loaders mods  (and datamods) support, and what each version supports.

### ISSUE THREAD

**Issue by realeatham** [CRLauncher/CRLauncher#3]

**Comment by TheEntropyShard** [comment]
Can you elaborate please?

**Comment by realeatham** [comment]
On the mod download screen, show what game versions and launchers it supports. Also, on the versions screen, show the same info for each version.

**Comment by TheEntropyShard** [comment]
Done in [89cb3fa](https://github.com/CRLauncher/CRLauncher/commit/89cb3fa3f87a6af961152794bff0059a7ef5374b)
