### ISSUE TITLE
When trying to update a mod from CRMM, it says mod alredy added.

### ISSUE THREAD

**Issue by realeatham** [CRLauncher/CRLauncher#5]
![image](https://github.com/user-attachments/assets/14a3dfeb-3586-4f2a-9512-b6c3e273fe88)

**Comment by TheEntropyShard** [comment]
It says that because it simply tries to add mod and does not check for version, and if the mod is already here, it just complains about duplicated id

**Comment by realeatham** [comment]
If it is easy, you should make it just replace the old mod even if it is thr same version.

**Comment by TheEntropyShard** [comment]
Done in [556ab0f](https://github.com/CRLauncher/CRLauncher/commit/556ab0fe2e9973c5b418a1695d710490fa373831)
